export const cursos =[
    {
        id: 1,
        nome: 'Informática para Internet',
        eixo: 'Informação e Comunicação',
        nivel:'Médio',
        forma_oferta:'Integrado',
        duracao_anos:3,
        municipio:'Naviraí',
        ano_inicio:2016,
    },
    {
        id: 2,
        nome: 'Informática para Internet',
        eixo: 'Informação e Comunicação',
        nivel:'Médio',
        forma_oferta:'Integrado',
        duracao_anos:3,
        municipio:'Dourados',
        ano_inicio:2015,
    },
    {
        id: 3,
        nome: 'Agricultura',
        eixo: 'Recursos Naturais',
        nivel:'Médio',
        forma_oferta:'Integrado',
        duracao_anos:3,
        municipio:'Naviraí',
        ano_inicio:2016,
    },
    {
        id: 4,
        nome: 'Agricultura',
        eixo: 'Recursos Naturais',
        nivel:'Médio',
        forma_oferta:'Integrado',
        duracao_anos:3,
        municipio:'Ponta Porã',
        ano_inicio:2010,
    },
    {
        id: 5,
        nome: 'Análise e Desenvolvimento de Sistemas',
        eixo: 'Informação e Comunicação',
        nivel:'Educação Superior',
        forma_oferta:'Tecnologia',
        duracao_anos:3,
        municipio:'Naviraí',
        ano_inicio:2016,
    },
    {
        id: 6,
        nome: 'Jogos Digitais',
        eixo: 'Informação e Comunicação',
        nivel:'Educação Superior',
        forma_oferta:'Tecnologia',
        duracao_anos:3,
        municipio:'Dourados',
        ano_inicio:2018,
    },
    {
        id: 7,
        nome: 'Agronomia',
        eixo: 'Recursos Naturais',
        nivel:'Educação Superior',
        forma_oferta:'Bacharelado',
        duracao_anos:5,
        municipio:'Naviraí',
        ano_inicio:2018,
    },




]